### ISSUE TITLE
some question about the PSMILES

### ISSUE THREAD

**Issue by jubaotianjing** [Ramprasad-Group/canonicalize_psmiles#2]
```
from canonicalize_psmiles.canonicalize import canonicalize
from rdkit import Chem
from rdkit.Chem import AllChem, Draw
import matplotlib.pyplot as plt

def DrawSMILES(smiles):
    molecule = Chem.MolFromSmiles(smiles)
    img = Draw.MolToImage(molecule)
    img.show()

smiles = "*c1cccc(C2=NC(N3CCCCC3)=NCCCCCN2N2C(=O)c3ccc4c5c(Br)cc6c7c(cc(Br)c(c8ccc(c3c48)C2=O)c75)C(=O)N(*)C6=O)c1"
DrawSMILES(smiles)
psmiles = canonicalize(smiles)
print(psmiles)
DrawSMILES(psmiles)
```

the output of DrawSMILES(smiles)
![image](https://github.com/Ramprasad-Group/canonicalize_psmiles/assets/65936223/f003cf08-3b23-49b5-846b-4fb467f005ee)

the outpput of DrawSMILES(psmiles)
![image](https://github.com/Ramprasad-Group/canonicalize_psmiles/assets/65936223/013248c8-5423-4f34-b07a-fdd9178d9913)

the display of PolymerGenome
![image](https://github.com/Ramprasad-Group/canonicalize_psmiles/assets/65936223/d597c67e-5619-48b0-bc03-731ea0dc7163)

obviously， the outputs of SMILES and PSMILES are different, since they show different polymer endpoints
Why does this situationoccur? Is it caused by any bugs?

**Comment by kuelumbus** [comment]
Please check this carefully again. This is not so obvious (check the positions of the "Br"s). The outputs (two drawings) are identical polymers. No bug.  PolymerGenome is also showing the correct drawing.

**Comment by jubaotianjing** [comment]
sorry, my bad, no questions
