### ISSUE TITLE
Add test cases to this package instead of psmiles

### ISSUE THREAD

**Issue by jdkern11** [Ramprasad-Group/canonicalize_psmiles#5]
Currently, pytest cases for this package are in the [psmiles package](https://github.com/Ramprasad-Group/psmiles)

This makes improving the canonicalization scheme challenging. For instance, an [issue](https://github.com/Ramprasad-Group/psmiles/issues/8) was raised that would require changing the package to improve it. The current scheme would be:
1. Test changes in this package manually first
2. Deploy the changes to the psmiles package
3. Run psmiles test cases
  - If they break, revert the changes in this package and repeat steps 1-3
  - If they pass, add the new edge case for future changes to test against and deploy new patch version

It would be easier to develop this package if pytests were located in this package instead:
1. Add new edge case to test cases
2. Develop package until all tests pass
3. Deploy new package version, updating patch version number (following major.minor.patch numbering scheme)
4. Change psmiles pyproject.toml to use latest version of package

**Comment by kuelumbus** [comment]
That's a good idea. Can you please review the PR?

**Comment by jdkern11** [comment]
Yes, I'll get to it this weekend!
